import json
from logging import info
import os
from pathlib import Path
import subprocess
import yaml
from .config import LabConfig
from .utils import container_exists, run, ensure_incus_running, get_container_state, info, success, warning, error, fatal

class Lab:
    def __init__(self, root: Path):
        self.root = root.absolute()
        self.config_path = self.root / "lab.yaml"
        self.config = LabConfig(self.config_path).load()
        self.nodes_dir = self.root / "nodes"
        self.shared_dir = self.root / "shared"

    @classmethod
    def init(cls, path: Path):
        """Initialize a new lab"""
        path.mkdir(exist_ok=True)
        lab = cls(path)
        lab.nodes_dir.mkdir(exist_ok=True)
        lab.shared_dir.mkdir(exist_ok=True)

        # Create git repo
        if not (path / ".git").exists():
            subprocess.run(["git", "init"], cwd=path, text=True)
            subprocess.run(["git", "add", "."], cwd=path, text=True)
            subprocess.run(["git", "commit", "-m", "labkit: initial commit"], cwd=path, input="init", text=True)

        # Create README
        readme = path / "README.md"
        if not readme.exists():
            readme.write_text(f"# {lab.config['name']}\n\nGenerated by labkit.\n")

        success(f"Lab initialized at {path}")
        info("Next: labkit node add <name>")
        return lab

    def add_node(self, name: str, template: str):
        """Add a new node (container) to the lab"""
        ensure_incus_running()

        # Use override or fallback to config
        effective_template = template or self.config["template"]

        if not container_exists(effective_template):
            error(f"Template container '{effective_template}' not found!")
            return
        
        if container_exists(name):
            error(f"Container '{name}' already exists!")
            return

        # Validate name
        if not name.replace("-", "").isalnum() or not name[0].islower():
            error("Invalid name: use lowercase letters, numbers, hyphens only")
            return

        # Check if exists
        if get_container_state(name):
            error(f"Container '{name}' already exists")
            return

        template = self.config["template"]
        info(f"Creating node '{name}' from template '{template}'...")
        success(f"Node '{name}' created and configured")

        # Clone container
        run(["incus", "copy", template, name], check=True)

        # Create node directory
        node_dir = self.nodes_dir / name
        node_dir.mkdir(exist_ok=True)

        # Create manifest.yaml
        manifest = node_dir / "manifest.yaml"
        manifest.write_text(f"""name: {name}
purpose: >-
  Replace with short description
role: unknown
tags: []
environment: development
owner: {self.config['user']}
lifecycle: experimental
created_via: labkit node add
dependencies: []
notes: |
  Add usage notes, gotchas, maintenance tips here.
""")

        # Create README.md
        readme = node_dir / "README.md"
        readme.write_text(f"# {name}\n\n> Update this with purpose and usage\n")

        # Mount node dir into container
        mount_point = self.config["node_mount"]["mount_point"]
        run([
            "incus", "config", "device", "add",
            name, "lab-node", "disk",
            f"path={mount_point}",
            f"source={node_dir}"
        ], check=True)

        # Mount shared dir
        if self.config["shared_storage"]["enabled"]:
            shared_mp = self.config["shared_storage"]["mount_point"]
            run([
                "incus", "config", "device", "add",
                name, "lab-shared", "disk",
                f"path={shared_mp}",
                f"source={self.shared_dir}"
            ], check=True)

        # Set labels
        run(["incus", "config", "set", name,
             f"user.lab={self.config['name']}",
             f"user.managed-by=labkit"])

        print(f"✅ Node '{name}' created and configured")
        print(f"📁 Docs: {node_dir}")
        print(f"🔗 Mounted: {node_dir} → {name}:{mount_point}")

        env = os.environ.copy()
        env.setdefault("GIT_AUTHOR_NAME", "labkit")
        env.setdefault("GIT_COMMITTER_NAME", "labkit")
        env.setdefault("GIT_AUTHOR_EMAIL", "labkit@localhost")
        env.setdefault("GIT_COMMITTER_EMAIL", "labkit@localhost")

        try:
            subprocess.run(
                ["git", "commit", "-m", f"labkit: added node {name}"],
                cwd=self.root,
                input="Auto-generated by labkit\n",
                text=True,
                check=True,
                env=env,
                timeout=30
            )
            success(f"Committed node metadata for '{name}'")
        except subprocess.CalledProcessError as e:
            warning(f"Git commit failed (no changes or config issue) — continuing anyway")
        except Exception as e:
            warning(f"Unexpected git error: {e}")

        # Auto-commit
        subprocess.run(["git", "add", "."], cwd=self.root, text=True)
        subprocess.run(["git", "commit", "-m", f"labkit: added node {name}"], cwd=self.root, input="auto", text=True)

    def remove_node(self, name: str, force: bool = False):
        """Remove a node"""
        state = get_container_state(name)
        if not state:
            print(f"❌ Container '{name}' not found")
            return

        if state == "Running" and not force:
            print(f"⚠️ '{name}' is running. Use --force to stop and delete.")
            return

        if force:
            run(["incus", "stop", name], check=True)
        run(["incus", "delete", name], check=True)

        print(f"🗑️ Deleted container '{name}'")

        # Don't delete node/ dir — keep history
        print(f"📘 Node metadata preserved in {self.nodes_dir}/{name}")

    def get_node_count(self):
        if not self.nodes_dir.exists():
            return 0
        return len([d for d in self.nodes_dir.iterdir() if d.is_dir()])
    
    def add_requirement(self, node_names):
        """Add one or more required external nodes (infrastructure dependencies)"""
        from .utils import run, info, warning, success

        lab_name = self.config["name"]

        # Ensure requirements list exists
        if "requires_nodes" not in self.config:
            self.config["requires_nodes"] = []

        updated_lab = False
        infra_updated = False

        for name in node_names:
            # 1. Check if container exists
            if not container_exists(name):
                warning(f"Container '{name}' does not exist")
                continue

            # 2. Add to lab.yaml if not already there
            if name not in self.config["requires_nodes"]:
                self.config["requires_nodes"].append(name)
                self.config["requires_nodes"].sort()
                updated_lab = True
                success(f"✅ Lab now requires: {name}")

                # 3. Update user.required_by on the node
                try:
                    result = run(
                        ["incus", "config", "get", name, "user.required_by"],
                        silent=True,
                        check=False,
                    )
                    current_labs = set()
                    if result.returncode == 0 and result.stdout.strip():
                        current_labs = set(result.stdout.strip().split(","))

                    if lab_name not in current_labs:
                        current_labs.add(lab_name)
                        new_value = ",".join(sorted(current_labs))
                        run([
                            "incus", "config", "set", name,
                            f"user.required_by={new_value}"
                        ], check=True)
                        info(f"🔗 {name}: added to user.required_by = {new_value}")
                        infra_updated = True
                except Exception as e:
                    warning(f"⚠️ Failed to update 'user.required_by' on {name}: {e}")

        # Save lab config if updated
        if updated_lab:
            self.save_config()
            if infra_updated:
                success("🔄 Infrastructure labels updated")

    def remove_requirement(self, node_names):
        """Remove one or more required external nodes"""
        from .utils import run, info, warning, success

        lab_name = self.config["name"]
        requires = self.config.get("requires_nodes", [])
        if not isinstance(requires, list):
            requires = []
            self.config["requires_nodes"] = []

        updated_lab = False
        infra_updated = False

        for name in node_names:
            if name in requires:
                requires.remove(name)
                updated_lab = True
                warning(f"🗑️ Removed requirement: {name}")

                # Try to remove from user.required_by
                try:
                    result = run(
                        ["incus", "config", "get", name, "user.required_by"],
                        silent=True,
                        check=False,
                    )
                    if result.returncode == 0 and result.stdout.strip():
                        current_labs = set(result.stdout.strip().split(","))
                        if lab_name in current_labs:
                            current_labs.remove(lab_name)
                            if current_labs:
                                new_value = ",".join(sorted(current_labs))
                                run([
                                    "incus", "config", "set", name,
                                    f"user.required_by={new_value}"
                                ], check=True)
                                info(f"🔗 {name}: removed '{lab_name}' from user.required_by")
                            else:
                                run(["incus", "config", "unset", name, "user.required_by"], check=True)
                                info(f"🔗 {name}: unset user.required_by (empty)")
                            infra_updated = True
                except Exception as e:
                    warning(f"⚠️ Failed to update 'user.required_by' on {name}: {e}")

        if updated_lab:
            self.config["requires_nodes"] = sorted(requires)
            self.save_config()
            success("📝 Updated lab requirements")
            if infra_updated:
                success("🔄 Infrastructure labels updated")

    def save_config(self):
        """Save current config back to lab.yaml"""
        data = {
            "name": self.config["name"],
            "template": self.config["template"],
            "user": self.config["user"],
            "managed_by": self.config["managed_by"]
        }
        if "requires_nodes" in self.config and self.config["requires_nodes"]:
            data["requires_nodes"] = self.config["requires_nodes"]
        (self.root / "lab.yaml").write_text(
            yaml.dump(data, indent=2, default_flow_style=False)
        )

def list_templates():
    result = run(["incus", "list", "--format=json"], silent=True)
    containers = json.loads(result.stdout)
    templates = [c for c in containers if c["config"].get("user.template") == "true"]
    for c in templates:
        print(f"📌 {c['name']}: {c.get('description', 'No description')}")